### ISSUE TITLE
#14 속도 더 빠르게

### ISSUE THREAD

**Issue by phg98** [taetaetae/github-repo-searcher#19]
#14 의 경우 하루에 한국사용자가 10명정도이기 때문에 하루씩 검색하지 않고 이틀씩 검색하면 속도가 거의 두배가 될 듯.
이틀씩 검색은 {date1}..{date2}로 레인지 검색하면 될 듯 함.
더 나아가면 전체한국사용자 약 4만명에 대해 이분법으로 찾아가면 최적의 횟수로 검색이 가능하지 않을까.....?

**Comment by AkiaCode** [comment]
그것도 좋지만 멀티스래드이나  멀티프로세스를 활용 해보는 건 어떤가요?

**Comment by taetaetae** [comment]
@AkiaCode 말씀하신 병렬 작업은 곧 api호출을 빠른시간내에 더 많이 호출하게 되는데 그럴경우 api 호출수 제한에 걸리게 됩니다.

**Comment by AkiaCode** [comment]
아하, 그 생각은 못 해봤네요..
