### ISSUE TITLE
search_month_range가 안 먹는다.

### ISSUE THREAD

**Issue by phg98** [taetaetae/github-repo-searcher#8]
개선은 못하고 이슈만 올려서 죄송합니다. ㅠㅠ
실행파라미터중에 search_month_range가 안 먹는것 같습니다. 문자로 처리되서 그런듯요. 
분할정복하려면 필요할듯하여 올립니다.

**Comment by taetaetae** [comment]
네 그렇네요. 문자 > 숫자로의 형 변환이 필요할 것 같습니다.

**Comment by phg98** [comment]
아직 수정안되었다면 수정해보겠습니닷
